/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.amazon.device.iap.model.RequestId;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testFoo() {
        RequestId requestId = new RequestId();
        System.out.println(requestId);
    }
}
